{{- if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metal-load-balancer-controller-manager
  namespace: {{ .Release.Namespace }}
  labels:
    app: kubernetes
    role: metal-load-balancer-controller-manager
    high-availability-config.resources.gardener.cloud/type: controller
spec:
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: kubernetes
      role: metal-load-balancer-controller-manager
  template:
    metadata:
      labels:
        gardener.cloud/role: controlplane
        app: kubernetes
        role: metal-load-balancer-controller-manager
        networking.resources.gardener.cloud/to-kube-apiserver-tcp-443: allowed
    spec:
      automountServiceAccountToken: false
      priorityClassName: gardener-system-300
      terminationGracePeriodSeconds: 0
      securityContext:
        fsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534
      containers:
        - name: metal-load-balancer-controller-manager
          image: {{ index .Values.images "metal-load-balancer-controller-manager" }}
          args:
            - --kubeconfig=/var/run/secrets/gardener.cloud/shoot/generic-kubeconfig/kubeconfig
            - --leader-election=true
            - --leader-election-namespace=kube-system
            - --health-probe-bind-address=:8083
            - --metrics-bind-address=:8084
            - --allocate-node-cidr={{ .Values.allocateNodeCIDRs }}
            - --node-cidr-mask-size={{ .Values.nodeCIDRMask }}
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 8083
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /readyz
              port: 8083
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          securityContext:
            allowPrivilegeEscalation: true
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - mountPath: /var/run/secrets/gardener.cloud/shoot/generic-kubeconfig
              name: kubeconfig
              readOnly: true
      volumes:
        - name: kubeconfig
          projected:
            defaultMode: 420
            sources:
              - secret:
                  items:
                    - key: kubeconfig
                      path: kubeconfig
                  name: {{ .Values.global.genericTokenKubeconfigSecretName }}
                  optional: false
              - secret:
                  items:
                    - key: token
                      path: token
                  name: shoot-access-metal-load-balancer-controller-manager
                  optional: false
{{- end }}
