apiVersion: v1
kind: ConfigMap
metadata:
  name: metallb-excludel2
  namespace: metallb-system
  labels:
    app.kubernetes.io/name: metallb
    app.kubernetes.io/instance: metallb
data:
  excludel2.yaml: |
    announcedInterfacesToExclude:
      - ^docker.*
      - ^cbr.*
      - ^dummy.*
      - ^virbr.*
      - ^lxcbr.*
      - ^veth.*
      - ^lo$
      - ^cali.*
      - ^tunl.*
      - ^flannel.*
      - ^kube-ipvs.*
      - ^cni.*
      - ^nodelocaldns.*
