{{- if .Values.ipAddressPool }}
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default
  namespace: {{ .Release.Namespace }}
spec:
  addresses:
{{- toYaml .Values.ipAddressPool | nindent 4 }}
{{- end }}
