apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: metallb-pod-lister
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: metallb
    app.kubernetes.io/instance: metallb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: metallb-pod-lister
subjects:
  - kind: ServiceAccount
    name: metallb-speaker
