apiVersion: v1
kind: ServiceAccount
metadata:
  name: metallb-speaker
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: metallb
    app.kubernetes.io/instance: metallb
    app.kubernetes.io/component: speaker
