apiVersion: v1
kind: ServiceAccount
metadata:
  name: metallb-controller
  namespace: metallb-system
  labels:
    app.kubernetes.io/name: metallb
    app.kubernetes.io/instance: metallb
    app.kubernetes.io/component: controller
