{{- if .Values.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metal-load-balancer-controller:speaker
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: metal-load-balancer-controller:speaker
subjects:
  - kind: ServiceAccount
    name: metal-load-balancer-controller-speaker
    namespace: kube-system
{{- end }}
