{{- if .Values.bgp.enabled }}
{{- if .Values.bgp.bgpPeer }}
{{- range $peer := .Values.bgp.bgpPeer }}
---
apiVersion: crd.projectcalico.org/v1
kind: BGPPeer
metadata:
  name: bgppeer-{{ $peer.asNumber }}-{{ $peer.peerIP }}
spec:
  asNumber: {{ $peer.asNumber }}
  {{- if $peer.nodeSelector }}
  nodeSelector: {{ $peer.nodeSelector }}
  {{- end }}
  peerIP: {{ $peer.peerIP }}
{{- end }}
{{- end }}
{{- end }}
