name: Release Helm Charts

on:
  push:
    branches:
      - main
    paths:
      - 'charts/gardener-extension-provider-ironcore-metal/**'
      - 'charts/gardener-extension-provider-ironcore-metal/**'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.16.2

      - name: Log in to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Determine chart version
        id: chart_version
        run: |
          echo "version=sha-$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: Package provider Helm chart
        run: |
          helm package charts/gardener-extension-provider-ironcore-metal --version ${{ steps.chart_version.outputs.version }}

      - name: Push provider Helm chart to GHCR
        run: |
          helm push gardener-extension-provider-ironcore-metal-${{ steps.chart_version.outputs.version }}.tgz oci://ghcr.io/${{ github.repository_owner }}/charts

      - name: Package admission Helm chart
        run: |
          helm package charts/gardener-extension-admission-ironcore-metal --version ${{ steps.chart_version.outputs.version }}

      - name: Push admission Helm chart to GHCR
        run: |
          helm push gardener-extension-admission-ironcore-metal-${{ steps.chart_version.outputs.version }}.tgz oci://ghcr.io/${{ github.repository_owner }}/charts
