name: Release Helm Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: bitdeps/helm-oci-charts-releaser@v0.1.3
        with:
          oci_registry: ghcr.io/${{ github.repository_owner }}/charts
          github_token: ${{ secrets.GITHUB_TOKEN }}
          oci_password: ${{ secrets.GITHUB_TOKEN }}
          oci_username: ${{ github.actor }}
